### ISSUE TITLE
Set vol.Detail to nil will break runV volumes

### ISSUE THREAD

**Issue by resouer** [hyperhq/hyperd#485]
**Problem Description:**

1. Validate() indeed has problem, see #487,  but this error will occur even when `Validate()` is removed.

2. In CRI frakti, it execute `RunPodSandbox` by using `kubeapi.PodSandboxConfig` to build a `hyperapi.UserPod` and this`PodSpec` like below to hyperd:
```
id:"k8s_POD.0_pod-vol_default_a130b1b1-c856-11e6-a8e5-080027e4bc93_05833cef" hostname:"pod-vol" labels:<key:"app" value:"web" > labels:<key:"io.kubernetes.frakti.a
nnotations" value:"{\"kubernetes.io/config.seen\":\"2016-12-22T09:55:07.860955418-05:00\",\"kubernetes.io/config.source\":\"api\"}" > labels:<key:"io.kubernetes.managed" value:"true" > labels:<key:"io.kubernetes.
pod.name" value:"pod-vol" > labels:<key:"io.kubernetes.pod.namespace" value:"default" > labels:<key:"io.kubernetes.pod.uid" value:"a130b1b1-c856-11e6-a8e5-080027e4bc93" > resource:<vcpu:1 memory:64 > dns:"8.8.8.8
" 
```

Please not that it **does not** have containers or volumes information, because `PodSandboxConfig` does not know such things.

But it seems hyperd expect containers and volumes information from `PodSpec` during `daemon.CreatePod`: https://github.com/hyperhq/hyperd/blob/master/daemon/pod/provision.go#L341-L354

So runv will report there's no such volume in `VmContext`: 
```
SB[vm-zFZOVpwrLe] Con[xxx] volume /var/lib/kubelet/pods/xxx does not exist in volume map
```

This does not break things like `hyperctl run -v /tmp:/test busybox`, because it will send a `PodSpec` with volume information:
```
id:"busybox-0253427955" resource:<vcpu:1 memory:128 > log:<> containers:<name:"busybox-0253427955" image:"busybox" restartPolicy:"never" tty:true command:"/bin/sh"
 volumes:<path:"/test" volume:"tmp94644" detail:<name:"tmp94644" source:"/tmp" format:"vfs" > > > 
```
 cc @feiskyer @gnawux

**Comment by resouer** [comment]
Tested with this Pod:
```
apiVersion: v1
kind: Pod
metadata:
  name: pod-vol 
  labels:
    app: web
spec:
  containers:
    - name: frontend
      image: nginx 
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80
      volumeMounts:
        - mountPath: /test-hostpath
          name: test-volume
  volumes:
  - name: test-volume
    hostPath:
      path: /tmp
```
